template/Dockerfile, template/cleanup-build-env.sh, template/config-build-env.sh, template/config-ols-admin_php.sh, template/config-ols.sh, template/prepare-ols-admin_php.sh
- fix(lsphp): Fixes missing shared libraries for running PHP under OLS.
- fix(admin_php): Fixes invalid build of the Web Console lsphp.
=> fix(php): Adds missing PHP runtime packages and builds proper admin_php

template/Dockerfile
fix(php): Adds support for copying the official php.ini files & available modules configurations from the official OLS Docker image.
=> Fixes Missing .ini Files for PHP

template/Dockerfile
- Fixes an invalid use of $PHP_MINOR_VERSION instead of $PHP_MAJOR_VERSION.
=> fix(php): Fixes invalid PHP version in .ini COPY from OLS image

.github/workflows/docker.yml
- Changes the GitHub Action to use the shell & `cut` command to split the PHP version string.
=> fix(github-actions): Changes the PHP version split step.

.github/workflows/docker.yml
- Updates the split PHP version step to use new setOutput handling.
- Fixes invalid reference to matrix variable.
=> fix(ci): Fixes invalid matrix value reference

.github/CODEOWNERS
- Adds a GitHub CODEOWNERS file to support PR auto-assignments.
=> feat: Adds support for CODEOWNERS

template/config-build-env.sh, template/config-php.sh
- Adds additional runtime & build packages for the Redis & Memcached PHP module features.
- Updates the PECL module installation to answer yes to the Redis & Memcached module installation features requests.
=> fix(php): Adds support for additional Redis & Memcached PHP module features

template/config-php.sh
- Changes the prompt responses to not attempt to use FastLZ.
=> fix(php): Fixes memcached PHP module installation failure

.github/workflows/docker.yml
* Adds release tag & changelog generation to GitHub Action workflow.
* Adds a GitHub Action workflow step to create a new release.
=> ci(GitHub): Updates GitHub Actions workflow to tag & release

.github/CODEOWNERS, .github/workflows/docker.yml, template/config-build-env.sh, template/config-php.sh
- feat: Adds support for CODEOWNERS (#13)
- fix(php): Adds support for additional Redis & Memcached PHP module features (#14)
- fix(php): Fixes memcached PHP module installation failure (#15)
- ci(GitHub): Updates GitHub Actions workflow to tag & release (#16)
=> fix(php): Fixes PHP modules & adds GitHub Releases support

.github/workflows/docker.yml
* Updates the GitHub Action steps for releases to ensure they are restricted to running only on the "latest" release.
=> fix(ci): Fixes GitHub Actions conditional expressions for releases

.github/workflows/docker.yml
* Updates the GitHub Action steps for releases to ensure they are restricted to running only on the "latest" release.
=> fix(ci): Fixes GitHub Actions conditional expressions for releases (#18)

.github/workflows/docker.yml
- Changes the GitHub Actions used for conventional commits changelogs & versions.
=> chore(ci): Fixes GitHub Actions releases wuth changelogs.

.github/workflows/docker.yml
- Changes the GitHub Actions used for conventional commits changelogs & versions.
=> chore(ci): Fixes GitHub Actions releases wuth changelogs. (#21)

.github/workflows/docker.yml
- Changes the GitHub Action used to generate the next version.
- Changes the GitHub Action used to generate the release notes.
=> chore(ci): Fixes autoamted GitHub Actions releases

.github/workflows/docker.yml
- Changes the GitHub Action used to generate the next version.
- Changes the GitHub Action used to generate the release notes.
=> chore(ci): Fixes autoamted GitHub Actions releases (#27)

.github/workflows/docker.yml
* Fixes the uses statement for the Universal Changelog Generator action.
=> chore(ci): Fixes bad GitHub Actions workflow (#29)

.github/workflows/docker.yml, template/config-ols.sh, template/config-php.sh
- Creates proper symlinks for teh fcgi lsphp after bad OLS compile bad binary is created.
=> fix(lsphp): Fixes invalid runtime lsphp binary and symlinks

.github/workflows/docker.yml, template/config-ols.sh, template/config-php.sh
* Creates proper symlinks for teh fcgi lsphp after bad OLS compile bad binary is created.
=> fix(lsphp): Fixes invalid runtime lsphp binary and symlinks (#31)

template/config-build-env.sh
- Adds `libjpeg-turbo-progs` package to provide `jpegtran` command.
- Adds `optipng` package.
- Adds `gifsicle` package.
=> feat(php): Adds additional runtime environment packages for image manipulation in PHP applications.

template/config-build-env.sh
- Adds `libjpeg-turbo-progs` package to provide `jpegtran` command.
- Adds `optipng` package.
- Adds `gifsicle` package.
=> feat(php): Adds additional runtime environment packages for image manipulation in PHP applications. (#45)

.github/workflows/docker.yml
- Updates the GitHub Action for easier PHP version management.
- Updates to PHP 8.2.1/8.1.14/8.0.27.
=> feat(php): Updates the versions of PHP to latest patch releases

.github/workflows/docker.yml
- Updates the GitHub Action for easier PHP version management.
- Updates to PHP 8.2.1/8.1.14/8.0.27.
=> feat(php): Updates the versions of PHP to latest patch releases (#47)

template/config-build-env.sh
* Adds `zip` package.
* Adds `unzip` package.
=> fix(system): Adds `zip` & `unzip` runtime packages for backup abilities

template/config-build-env.sh
* Adds `zip` package.
* Adds `unzip` package.
=> fix(system): Adds `zip` & `unzip` runtime packages for backup abilities (#50)

template/Dockerfile, template/config-build-env.sh, template/prepare-build.sh, template/prepare-ols.sh
- Adds ModSecurity module build to Docker image build process.
- Adds support for NodeJS 16.
- Adds support for Ruby.
=> feat(ols): Adds additional module & server language(Node & Ruby) support.

template/Dockerfile, template/config-build-env.sh, template/prepare-build.sh, template/prepare-ols.sh
- Adds ModSecurity module build to Docker image build process.
- Adds support for NodeJS 16.
- Adds support for Ruby.
=> feat(ols): Adds additional module & server language(Node & Ruby) support. (#55)

.github/dependabot.yml
- Adds support for Dependebot to keep the GitHub Actions used up-to-date.
=> chore: Updates the Dependebot configuration for GitHub Actions

template/Dockerfile, template/ols_htaccess
- Adds a system crontab to find updated `.htaccess` files and restart OLS if a file has changed since OLS was last started.
=> feat(ols): Adds support for semi-automatic .htaccess file parsing

.github/workflows/docker.yml
* Updates PHP 8.2 to 8.2.3.
* Updates PHP 8.1 to 8.1.16.
* Updates PHP 8.0 to 8.0.28.
=> fix(php): Updates PHP to the latest releases

.github/workflows/docker.yml, template/Dockerfile, template/ols_htaccess
- chore(deps): Bump docker/build-push-action from 3 to 4 (#65)
- feat(ols): Adds support for semi-automatic .htaccess file parsing (#67)
- fix(php): Updates PHP to the latest releases (#68)
=> Feature & Updates Release

.github/dependabot.yml, .github/workflows/docker.yml
- chore(ci): Fixes Dependabot configuration with correct path to the Dockerfile (#71)
- chore(ci): Changes GitHub Actions workflow to deploy to GitHub Packages instead of Docker Hub (#72)
=> CI/CD Dependency Monitoring & Registry Migration Release

.github/workflows/docker.yml
- Updates to PHP 8.1.18.
- Updates to PHP 8.2.5.
=> fix(php): Updates PHP 8 to latest releases as of 2023-04-13

.github/workflows/docker.yml
* Adds the `provenance: false` buildx configuration and fixes #81 .
=> fix(docker): Fixes OCI headers for compatibility issues

.github/workflows/docker.yml
* Adds the `provenance: false` buildx configuration and fixes #81 .
=> fix(docker): Fixes OCI headers for compatibility issues (#82)

.github/workflows/docker.yml
* Updates the PHP 8.2 release to the latest version.
* Applies available Debian security updates.
=> fix(php): Updates PHP 8.2 to v8.2.6

.github/workflows/docker.yml
* Updates the PHP 8.2 release to the latest version.
* Applies available Debian security updates.
=> fix(php): Updates PHP 8.2 to v8.2.6 (#86)

.github/workflows/docker.yml
* Updates the build matrix to support the latest 8.1.19 PHP release.
=> fix(php): Updates PHP 8.1 build to latest 8.1.19 release

.github/workflows/docker.yml
* Updates the build matrix to support the latest 8.1.19 PHP release.
=> fix(php): Updates PHP 8.1 build to latest 8.1.19 release (#88)

.github/workflows/docker.yml
- Updates the GitHub Actions configuration to build the latest version of OpenLiteSpeed.
=> feat(ols): Update to latest v1.7.17 version of OpenLiteSpeed

.github/workflows/docker.yml
* Updates the GitHub Actions configuration to build the latest version of OpenLiteSpeed.
=> feat(ols): Update to latest v1.7.17 version of OpenLiteSpeed (#96)

.github/workflows/docker.yml
- Upgrades the PHP 8.2 image to [8.2.8](https://www.php.net/ChangeLog-8.php#8.2.8).
- Upgrades the PHP 8.1 image to [8.1.21](https://www.php.net/ChangeLog-8.php#8.1.21).
=> feat(php): Upgrades to PHP 8.2.8 & 8.1.21

.github/workflows/docker.yml
- Upgrades the PHP 8.2 image to [8.2.8](https://www.php.net/ChangeLog-8.php#8.2.8).
- Upgrades the PHP 8.1 image to [8.1.21](https://www.php.net/ChangeLog-8.php#8.1.21).
=> feat(php): Upgrades to PHP 8.2.8 & 8.1.21 (#99)

.github/workflows/docker.yml, .github/workflows/test-builds.yml, template/Dockerfile, template/cleanup-build-env.sh, template/config-build-env.sh, template/config-ols.sh, template/prepare-build.sh, template/prepare-ols.sh, template/prepare-runtime.sh
* feat(OpenLiteSpeed): Upgrades OpenLiteSpeed to version 1.7.18.
* Fixes #105 
* feat(PHP): Upgrades PHP to 8.0.30/8.1.22/8.2.9.
* Fixes #104 
* chore(build): Changes build to use official OLS repository for OLS installation.
* chore(testing): Adds PR builds & testing.
=> feat: Upgrades OpenLiteSpeed & PHP to Latest Versions

.github/workflows/docker.yml, .github/workflows/test-builds.yml, README.md
- Updates the Docker image tagging to add additional tags to allow users to get updates for OpenLiteSpeed but stick to a specific version of PHP.
- Updates the README to include the listing of available tags.
=> feat(Docker): Adds build support and documentation for more tags

.github/workflows/docker.yml, .github/workflows/test-builds.yml, README.md
- Upgrades PHP 8.2 to 8.2.10. Fixes #111
- Upgrades PHP 8.1 to 8.1.23. Fixes #111
- Updates README with missing version tags.
=> feat(PHP): Upgrades PHP to 8.2.10, 8.1.23

.github/workflows/docker.yml, .github/workflows/test-builds.yml, README.md
- feat(PHP): Upgrades PHP to 8.2.10, 8.1.23 (#112)
- chore(deps): Bump ncipollo/release-action from 1.12.0 to 1.13.0 (#110)
=> feat(php): PHP Upgrades Release

.github/workflows/docker.yml, .github/workflows/test-builds.yml
- Fixes #119.
- Upgrades PHP 8.1 to 8.1.24 release.
- Upgrades PHP 8.2 to 8.2.11 release.
=> fix(PHP): Upgrades PHP to Latest 8.1 & 8.2 Releases

README.md, template/Dockerfile
* Updates README.
* Updates Dockerfile metadata.
=> fix(OLS): Updates for the OpenLiteSpeed 1.7.18.1 Patch (#123)

.github/workflows/docker.yml, .github/workflows/test-builds.yml
=> fix(PHP): Updates PHP 8.2 to 8.2.12

.github/workflows/docker.yml, .github/workflows/test-builds.yml
- Updates PHP 8.1 to 8.1.26 release.
- Updates PHP 8.2 to 8.2.13 release.
=> fix(PHP): Updates to latest PHP 8.1 & 8.2 bugfix release

.github/workflows/docker.yml, .github/workflows/test-builds.yml
- Updates PHP 8.1 to 8.1.26 release.
- Updates PHP 8.2 to 8.2.13 release.
=> fix(PHP): Updates to latest PHP 8.1 & 8.2 bugfix release (#130)

.github/workflows/docker.yml, .github/workflows/test-builds.yml, README.md
- Fixes #133
- Adds PHP 8.3 builds.
=> feat(PHP): Adds support for PHP 8.3

.github/workflows/docker.yml, .github/workflows/test-builds.yml
- Updates PHP 8.3 to 8.3.1.
- Updates PHP 8.2 to 8.2.14.
- Updates PHP 8.1 to 8.1.27.
=> fix(PHP): Updates PHP versions to latest 2023-12-21 releases (#137)

.github/workflows/docker.yml, .github/workflows/test-builds.yml
- Updates PHP 8.2 to 8.2.15.
- Updates PHP 8.3 to 8.3.2.
=> fix(PHP): Updates PHP 8.2 & 8.3 to Latest Versions

.github/workflows/docker.yml, .github/workflows/test-builds.yml
- Updates OpenLiteSpeed from 1.7.18 to 1.7.19.
=> fix(OpenLiteSpeed): Updates OpenLiteSpeed to Latest 1.7 Release

.github/workflows/docker.yml
- Fixes Node matrix tagging errors.
=> fix(CI/CD): Fixes release GitHub Actions workflow

template/config-build-env.sh
- Fixes #150 
- Updates the runtime packages list for builds to include the `webp` package.
=> feat(Image Optimization): Adds WebP CLI for use in image optimization

.github/workflows/docker.yml, .github/workflows/test-builds.yml
- Fixes #154
- Upgrades PHP 8.3 (8.3.2 -> 8.3.3): https://www.php.net/ChangeLog-8.php#8.3.3
- Upgrades PHP 8.2 (8.2.15 -> 8.2.16): https://www.php.net/ChangeLog-8.php#PHP_8_2
- Fixes #153
- NodeJS 18 (18.19.0 -> 18.19.1): https://nodejs.org/en/blog/release/v18.19.1
- NodeJS 20 (20.11.0 -> 20.11.1): https://nodejs.org/en/blog/release/v20.11.1
=> fix(deps): PHP 8.3/8.2 Patches & NodeJS Security Updates

.github/workflows/docker.yml, .github/workflows/test-builds.yml, template/config-build-env.sh
- feat(Image Optimization): Adds WebP CLI for use in image optimization (#151)
- chore(deps): Bump ncipollo/release-action from 1.13.0 to 1.14.0 (#152)
- fix(deps): PHP 8.3/8.2 Patches & NodeJS Security Updates (#155)
=> 2024-02-16 Dependency Updates Release

.github/workflows/docker.yml, .github/workflows/test-builds.yml
- Updates PHP 8.2 to 8.2.17.
- Updates PHP 8.3 to 8.3.4.
=> fix(PHP): Updates PHP versions to latest patch releases

.github/workflows/docker.yml, .github/workflows/test-builds.yml
- Updates PHP 8.2 to 8.2.17.
- Updates PHP 8.3 to 8.3.4.
- Rebuild w/ Latest NodeJS Security Releases.
=> fix(PHP): Updates PHP versions to latest patch releases (#158)

.github/workflows/docker.yml, .github/workflows/test-builds.yml
- Updates NodeJS to latest security release versions.
- Updates PHP 8.2.17 to 8.2.18, 8.3.4 to 8.3.6.
=> fix(deps): Updates PHP & NodeJS to latest versions

.github/workflows/docker.yml, .github/workflows/test-builds.yml
- Updates NodeJS to latest security release versions.
- Updates PHP 8.2.17 to 8.2.18, 8.3.4 to 8.3.6.
=> 2024-04-11 Updates Release

.github/workflows/docker.yml, .github/workflows/test-builds.yml
- Updates PHP 8.1 to version 8.1.28.
=> fix(PHP): Updates PHP 8.1 to latest version

.github/workflows/docker.yml, .github/workflows/test-builds.yml
- Updates PHP 8.1 to version 8.1.28.
=> 2024-04-14 PHP Upgrade Release

.github/workflows/docker.yml, .github/workflows/test-builds.yml
- Fixes #166
- Updates the GitHub Action workflows to build the Admin control panel PHP version with the same PHP version as for vhosts.
=> feat(Admin): Makes upgraded PHP for Admin control panel standard

.github/workflows/docker.yml, .github/workflows/test-builds.yml
- Fixes #170
- Updates PHP 8.3 to 8.3.8.
- Updates PHP 8.2 to 8.2.20.
- Updates PHP 8.1 to 8.1.29.
=> fix(PHP): Updates PHP 8.3/8.2/8.1 to latest 2024-06-06 releases

.github/workflows/docker.yml, .github/workflows/test-builds.yml
- feat(Admin): Makes upgraded PHP for Admin control panel standard (#169)
- **fix(PHP): Updates PHP 8.3/8.2/8.1 to latest 2024-06-06 releases (#173)**
=> 2024-06-12 PHP Patching Release

.github/workflows/docker.yml, .github/workflows/test-builds.yml
- Updates PHP 8.3 to 8.3.10.
- Updates PHP 8.2 to 8.2.22.
=> fix(PHP): Updates PHP to latest releases as of 2024-08-06

.github/workflows/docker.yml, .github/workflows/test-builds.yml
- Updates PHP 8.3 to 8.3.10.
- Updates PHP 8.2 to 8.2.22.
=> fix(PHP): Updates PHP to latest releases as of 2024-08-06 (#177)

.github/workflows/docker.yml, .github/workflows/test-builds.yml
- Updates PHP 8.3.10 -> 8.3.12.
- Updates PHP 8.2.22 -> 8.2.24.
- Updates PHP 8.1.29 -> 8.1.30.
=> fix(PHP) 2024-10-03 Updates PHP to latest security releases

.github/workflows/docker.yml, .github/workflows/test-builds.yml
- Updates PHP 8.3.10 -> 8.3.12.
- Updates PHP 8.2.22 -> 8.2.24.
- Updates PHP 8.1.29 -> 8.1.30.
=> fix(PHP): 2024-10-03 Updates PHP to latest security releases (#179)

.github/workflows/docker.yml, .github/workflows/test-builds.yml, template/Dockerfile
- Updates PHP 8.1/8.2/8.3 to latest releases.
- Updates NodeJS 18/20 to latest releases.
- Adds PHP 8.4 release.
- Adds NodeJS 22 LTS release.
=> feat(Languages): Updates PHP/NodeJS versions & adds latest PHP/NodeJS stable releases

.github/workflows/docker.yml, .github/workflows/test-builds.yml, template/Dockerfile
- Updates PHP 8.1/8.2/8.3 to latest releases.
- Updates NodeJS 18/20 to latest releases.
- Adds PHP 8.4 release.
- Adds NodeJS 22 LTS release.
- Updates to OpenLiteSpeed 1.8.3.
=> feat(Languages): Updates PHP/NodeJS versions & adds latest PHP/NodeJS stable releases (#185)

.github/workflows/docker.yml, .github/workflows/test-builds.yml, README.md
- Updates PHP 8.4 to 8.4.7.
- Updates PHP 8.3 to 8.3.21.
- Updates PHP 8.2 to 8.2.28.
- Updates ncipollo/release-action to v1.16.0.
- Updates README with latest tags.
=> fix(PHP): Updates PHP to latest releases

.github/workflows/docker.yml, .github/workflows/test-builds.yml, README.md
- Updates PHP 8.4 to 8.4.7.
- Updates PHP 8.3 to 8.3.21.
- Updates PHP 8.2 to 8.2.28.
- Updates ncipollo/release-action to v1.16.0.
- Updates README with latest tags.
=> fix(PHP): Updates PHP to latest releases (#188)
